AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: "The name of the environment this logging bucket is being deployed into."
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"

Resources:
  S3ServerAccessLogsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
        - '-'
        - - !Ref AWS::AccountId
          - 's3-server-access-logs'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls: 
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      LifecycleConfiguration:
        Rules:
          - Id: BucketExpiry
            Status: Enabled
            ExpirationInDays: 30
      Tags:
        - Key: StackName
          Value: AWS::StackName
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: central-sre
        - Key: Source
          Value: "govuk-one-login/central-sre-utils/cloudformation/s3-server-access-logs/template.yaml"

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3ServerAccessLogsBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: RestrictToSameAccount
            Action:
              - 's3:PutObject'
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Resource: !Sub "arn:${AWS::Partition}:s3:::${S3ServerAccessLogsBucket}/*"
            Condition:
              StringEquals:
                'aws:SourceAccount': !Sub '${AWS::AccountId}'
          - Sid: AllowSSLRequestsOnly
            Action: "s3:*"
            Effect: Deny 
            Principal: "*"
            Resource:
              - !Sub ${S3ServerAccessLogsBucket.Arn}
              - !Sub ${S3ServerAccessLogsBucket.Arn}/*
            Condition: 
              Bool:
                "aws:SecureTransport": "false"
      
Outputs:
  S3ServerAccessLogsBucketName:
    Value: !Ref S3ServerAccessLogsBucket
    Description: Name of the sample Amazon S3 bucket with a logging configuration.
  